
language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - node
  - lts/*
script:
  - npm test
after_success:
  - npx codecov
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"